apiVersion: v1
kind: Service
metadata: 
  name: "{{ .Values.applicationName }}-svc"
  namespace: {{ .Values.namespace }}
  labels:
    app: "{{ .Values.applicationName }}-svc"
spec:
  selector:
    app: {{ .Values.applicationName }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      name: webport